'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const themeJson = JSON.parse(fs.readFileSync(path.join(ROOT, 'theme.json'), 'utf8'));
const configJson = JSON.parse(fs.readFileSync(path.join(ROOT, 'config.json'), 'utf8'));

function generateColors() {
	const palette = themeJson.settings.color.palette;
	let out = '// This file generated with build process using theme.json\n';
	out += '// Do not edit this file directly\n\n';

	for (const item of palette) {
		out += `$${item.slug}: ${item.color};\n`;
	}

	out += '\n\n';

	for (const item of palette) {
		out += `.has-${item.slug}-color {\n color: $${item.slug};\n}\n`;
		out += `.has-${item.slug}-background-color {\n background-color: $${item.slug};\n}\n`;
		out += `.has-${item.slug}-border-color {\n border-color: $${item.slug};\n border-style: solid;\n}\n`;
	}

	out += '\n\n';
	out += '@media (max-width: 767px){\n';
	for (const item of palette) {
		out += `.block-half-screen-content .wp-block-column.has-${item.slug}-background-color {\n`;
		out += ` background-color: $${item.slug} !important;\n}\n\n`;
	}
	out += '\n}';

	fs.writeFileSync(path.join(ROOT, 'assets/scss/_colors.scss'), out);
	console.log('Generated _colors.scss');
}

function generateEditorFormats() {
	const formats = configJson.editor_formats;
	let out = '/**\n';
	out += ' * This file generated with build process using config.json\n';
	out += ' * Do not edit this file directly — it will be overwritten on build\n';
	out += ' * Copy selectors into a new SCSS file to use them\n';
	out += ' **/\n\n';

	for (const [key, val] of Object.entries(formats)) {
		out += `// ${val.label} Editor Format\n`;
		out += `.is-style-${key} {\n}\n\n`;
	}

	fs.writeFileSync(path.join(ROOT, 'assets/scss/_editor-formats-reference.scss'), out);
	console.log('Generated _editor-formats-reference.scss');
}

generateColors();
generateEditorFormats();
